---
title: "Figure1 panels of MACARRoN manuscript"
author: "Amrisha Bhosle"
date: "2024-01-24"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages, message=FALSE}
library(ggplot2)
library(data.table)
library(tidyverse)
library(readxl)
library(RColorBrewer)
```

```{r addSmallLegend}
addSmallLegend <- function(myPlot, pointSize = 1, textSize = 9, spaceLegend = 0.5) {
  myPlot +
    guides(shape = guide_legend(override.aes = list(size = pointSize)),
           color = guide_legend(override.aes = list(size = pointSize))) +
    theme(legend.title = element_text(size = textSize), 
          legend.text  = element_text(size = textSize),
          legend.key.size = unit(spaceLegend, "lines"),
          legend.box.margin = margin(-10,-10,-10,-10))
}
```

### Figure 1A
```{r figure 1A, fig.width=7.5, fig.height=2.5}
met_types <- read_excel("data/Dataset_EV1.xlsx", sheet = 1) |> as.data.frame()
hmp2_abun <- read.csv("../../input/hmp2_intensities.csv")
hmp2_meta <- read.csv("../../input/hmp2_metadata.csv", row.names = 1)
transform_col <- function(col){
  mets <- met_types$`Annotation type`
  mets[which(is.na(col))] <- NA
  mets
}
met_df <- apply(hmp2_abun, 2, transform_col) |> as.data.frame()
feat_dist_by_sample <- apply(met_df, 2, table) %>%
  as.data.frame() %>%
  rownames_to_column() %>%
  pivot_longer(-1) %>%
  rename("type" = 1, "sample" = 2) %>%
  group_by(sample) %>%
  mutate(total = sum(value)) %>%
  ungroup() %>%
  arrange(total) %>%
  mutate(diagnosis = hmp2_meta[sample, "diagnosis"]) %>%
  mutate(colfacet = case_when(
    diagnosis == "Control" ~ "non-IBD (n = 135)",
    diagnosis == "CD" ~ "CD (n = 265)",
    diagnosis == "UC" ~ "UC (n = 146)")) %>%
  mutate(type = factor(type, levels = c("standard","putative mass-match","unknown"))) %>%
  mutate(colfacet = factor(colfacet, levels = c("non-IBD (n = 135)","CD (n = 265)","UC (n = 146)"))) %>%
  mutate(sample = factor(sample, levels=unique(sample)))

# plot
fig1A <- ggplot(feat_dist_by_sample, aes(x=sample, y=value, fill=type)) + 
  geom_bar(stat="identity", width = 1)+scale_fill_manual(values=c("firebrick1","lightsteelblue1","grey50")) +
  xlab("Samples")+ ylab("Features") + 
  facet_grid(cols=vars(colfacet), space="free", scales="free")  + theme_bw() + 
  theme(axis.ticks.x = element_blank(), axis.text.x = element_blank(), legend.position="bottom",
        axis.title.x = element_text(size=10), axis.title.y = element_text(size=10), 
        axis.text.y = element_text(size=8), strip.text.x = element_text(size = 10),
        panel.background = element_rect(fill="white")) +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) +
  scale_y_continuous(breaks = scales::pretty_breaks(n = 8)) + guides(fill=guide_legend(nrow=1)) + labs(fill="Feature category")
addSmallLegend(fig1A)
```

### Figure 1B
```{r abundance and prevalence of features}
abundance <- rowMeans(log2(hmp2_abun + 1), na.rm=TRUE) # vector is 'mean log2(abundance)' in met_types
prevalence <- rowMeans(!is.na(hmp2_abun)) # vector is 'prevalence' in met_types
```

```{r figure 1B, fig.width=7.5, fig.height=2.5}
fig1B_df <- met_types[,c(7,8,9)] %>%
  rename("type" = 1, "prev" = 2, "abun" = 3) %>%
  mutate(type = factor(type, levels = c("standard","putative mass-match","unknown")))
col = brewer.pal(n = 9, name = "RdYlBu")

# plot
fig1B <- ggplot(fig1B_df, aes(prev,abun)) + geom_bin2d() + 
  scale_fill_gradientn(colors = rev(col)) + xlab("Prevalence") + 
  ylab(expression(mean ~log[2]~(Abundance))) + theme_bw() +
  facet_grid(cols=vars(type), scales = "free", space="free") + 
  theme(axis.title.x = element_text(size=10), axis.title.y = element_text(size=10),
        axis.text.y = element_text(size=8), axis.text.x = element_text(size=8), 
        strip.text.x = element_text(size=10))
addSmallLegend(fig1B)
```

### Figure 1C
```{r figure 1C, fig.width=7.5, fig.height=3.5}
CD_stats <- read.csv("../../output/all_CD_priority_scores.csv")
UC_stats <- read.csv("../../output/all_UC_priority_scores.csv")
col = brewer.pal(n = 9, name = "RdYlBu")
fig1C_df <- rbind(CD_stats[,c("Compound","effect_size","qvalue","type","Status")] %>%
  mutate(phenotype = "CD.dys"),UC_stats[,c("Compound","effect_size","qvalue","type", "Status")] %>%
  mutate(phenotype = "UC")) %>%
  mutate(effect_size = ifelse(Status %like% "depleted", effect_size*-1, effect_size)) %>%
  mutate(type = factor(type, levels = c("standard","putative mass-match","unknown"))) %>%
  as.data.frame()

fig1C <- ggplot(fig1C_df, aes(as.numeric(effect_size), -log10(as.numeric(qvalue)))) + 
  geom_bin2d() + theme_bw() +
  facet_grid(cols=vars(type), rows=vars(phenotype), scales="free", space="free") + 
  xlab("coefficient") + ylab(expression(-log[10]~(q-value))) +
  scale_fill_gradientn(colors = rev(col)) + 
  theme(axis.title.x = element_text(size=10), axis.title.y =element_text(size=10), 
        axis.text.y = element_text(size=10), axis.text.x = element_text(size=10),
        strip.text.x = element_text(size=10),strip.text.y = element_text(size=10))  
addSmallLegend(fig1C)
```