---
title: "Figure3 of MACARRoN manuscript"
author: "Amrisha Bhosle"
date: "2024-01-25"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages, message=FALSE}
library(ggplot2)
library(data.table)
library(tidyverse)
library(cowplot)
library(viridis)
```

```{r addSmallLegend}
addSmallLegend <- function(myPlot, pointSize = 1, textSize = 9, spaceLegend = 0.5) {
  myPlot +
    guides(shape = guide_legend(override.aes = list(size = pointSize)),
           color = guide_legend(override.aes = list(size = pointSize))) +
    theme(legend.title = element_text(size = textSize), 
          legend.text  = element_text(size = textSize),
          legend.key.size = unit(spaceLegend, "lines"),
          legend.box.margin = margin(-10,-10,-10,-10))
}
```


```{r addSmallLegend2}
addSmallLegend2 <- function(myPlot, pointSize = 1, textSize = 8, spaceLegend = 0.5) {
  myPlot +
    guides(shape = guide_legend(override.aes = list(size = pointSize)),
           color = guide_legend(override.aes = list(size = pointSize))) +
    theme(legend.title = element_text(size = textSize), 
          legend.text  = element_text(size = textSize),
          legend.key.size = unit(spaceLegend, "lines"),
          legend.box.margin = margin(-10,-10,-10,-10))
}
```

### Figure 3
```{r figure 3, fig.height=7.25, fig.width=8.75, message=FALSE, warning=FALSE}
CD_stats <- read.csv("../../output/all_CD_priority_scores.csv")
UC_stats <- read.csv("../../output/all_UC_priority_scores.csv")
chem_tax <- read.csv("../../input/hmdb_taxonomy.csv")

annotated_modules <- unique(CD_stats[CD_stats$Covaries_with_standard == 1,"Module"])
modules <- as.data.frame(table(CD_stats$Module)) %>%
  rename(module = 1, size = 2) %>%
  mutate(module = as.numeric(as.character(module))) %>%
  filter(module > 0) %>%
  mutate(type = ifelse(module %in% annotated_modules, "annotated", "unannotated"))

# modules containing IBD enriched features
annotated_modules_df <- modules[modules$module %in% annotated_modules,]
annotated_modules_df$CD_enr <- vapply(annotated_modules_df$module, function(x) 
  length(CD_stats[CD_stats$Module ==x & CD_stats$Status == "enriched in CD.dys" & CD_stats$qvalue < 0.05,1]), numeric(1))
annotated_modules_df$UC_enr <- vapply(annotated_modules_df$module, function(x) 
  length(UC_stats[UC_stats$Module ==x & UC_stats$Status == "enriched in UC" & UC_stats$qvalue < 0.05,1]), numeric(1))
# modules containing IBD depleted features
annotated_modules_df$CD_dep <- vapply(annotated_modules_df$module, function(x) 
  length(CD_stats[CD_stats$Module ==x & CD_stats$Status == "depleted in CD.dys" & CD_stats$qvalue < 0.05,1]), numeric(1))
annotated_modules_df$UC_dep <- vapply(annotated_modules_df$module, function(x) 
  length(UC_stats[UC_stats$Module ==x & UC_stats$Status == "depleted in UC" & UC_stats$qvalue < 0.05,1]), numeric(1))

#fractions that are perturbed
annotated_modules_df <- annotated_modules_df %>%
  mutate(CD_enr_frac = CD_enr/size,
         UC_enr_frac = UC_enr/size,
         CD_dep_frac = CD_dep/size,
         UC_dep_frac = UC_dep/size)

# modules that contain 25% of each category
CD_enr_modules <- annotated_modules_df[annotated_modules_df$CD_enr_frac >= 0.25,"module"]
CD_dep_modules <- annotated_modules_df[annotated_modules_df$CD_dep_frac >= 0.25,"module"]
UC_enr_modules <- annotated_modules_df[annotated_modules_df$UC_enr_frac >= 0.25,"module"]
UC_dep_modules <- annotated_modules_df[annotated_modules_df$UC_dep_frac >= 0.25,"module"]

#--------------------------------------------------------
# Heatmap that shows taxonomy of standards in each module
#--------------------------------------------------------

CD_enr_tax_df <- CD_stats[CD_stats$Module %in% CD_enr_modules, c("Module","HMDB.ID")] %>%
  rename(module=1, hmdb=2) %>%
  filter(!grepl("\\*", hmdb)) %>%
  filter(hmdb %like% "HMDB") %>%
  mutate(subclass = vapply(hmdb, function(x) chem_tax[chem_tax$HMDB.ID == x, "Sub_Class"], character(1))) %>%
  mutate(class = vapply(hmdb, function(x) chem_tax[chem_tax$HMDB.ID == x, "Class"], character(1))) %>%
  mutate(taxonomy = ifelse(subclass == "", paste0(class,"*"), subclass)) %>%
  group_by(module, taxonomy) %>%
  tally() %>%
  mutate(type = "CD-dys enriched") %>%
  arrange(desc(n),taxonomy) %>%
  mutate(module = factor(module, levels=unique(module))) %>%
  mutate(taxonomy = factor(taxonomy, levels=unique(taxonomy)))

CD_dep_tax_df <- CD_stats[CD_stats$Module %in% CD_dep_modules, c("Module","HMDB.ID")] %>%
  rename(module=1, hmdb=2) %>%
  filter(!grepl("\\*", hmdb)) %>%
  filter(hmdb %like% "HMDB") %>%
  mutate(subclass = vapply(hmdb, function(x) chem_tax[chem_tax$HMDB.ID == x, "Sub_Class"], character(1))) %>%
  mutate(class = vapply(hmdb, function(x) chem_tax[chem_tax$HMDB.ID == x, "Class"], character(1))) %>%
  mutate(taxonomy = ifelse(subclass == "", paste0(class,"*"), subclass)) %>%
  group_by(module, taxonomy) %>%
  tally() %>%
  mutate(type = "CD-dys depleted") %>%
  arrange(desc(n),taxonomy) %>%
  mutate(module = factor(module, levels=unique(module))) %>%
  mutate(taxonomy = ifelse(module == 217, "Alkaloids and derivatives",taxonomy)) %>%
  mutate(taxonomy = factor(taxonomy, levels=unique(taxonomy)))

UC_enr_tax_df <- CD_stats[CD_stats$Module %in% UC_enr_modules, c("Module","HMDB.ID")] %>%
  rename(module=1, hmdb=2) %>%
  filter(!grepl("\\*", hmdb)) %>%
  filter(hmdb %like% "HMDB") %>%
  mutate(subclass = vapply(hmdb, function(x) chem_tax[chem_tax$HMDB.ID == x, "Sub_Class"], character(1))) %>%
  mutate(class = vapply(hmdb, function(x) chem_tax[chem_tax$HMDB.ID == x, "Class"], character(1))) %>%
  mutate(taxonomy = ifelse(subclass == "", paste0(class,"*"), subclass)) %>%
  group_by(module, taxonomy) %>%
  tally() %>%
  mutate(type = "UC enriched") %>%
  arrange(desc(n),taxonomy) %>%
  mutate(module = factor(module, levels=unique(module))) %>%
  mutate(taxonomy = factor(taxonomy, levels=unique(taxonomy)))

UC_dep_tax_df <- CD_stats[CD_stats$Module %in% UC_dep_modules, c("Module","HMDB.ID")] %>%
  rename(module=1, hmdb=2) %>%
  filter(!grepl("\\*", hmdb)) %>%
  filter(hmdb %like% "HMDB") %>%
  mutate(subclass = vapply(hmdb, function(x) chem_tax[chem_tax$HMDB.ID == x, "Sub_Class"], character(1))) %>%
  mutate(class = vapply(hmdb, function(x) chem_tax[chem_tax$HMDB.ID == x, "Class"], character(1))) %>%
  mutate(taxonomy = ifelse(subclass == "", paste0(class,"*"), subclass)) %>%
  group_by(module, taxonomy) %>%
  tally() %>%
  mutate(type = "UC depleted") %>%
  arrange(desc(n),taxonomy) %>%
  mutate(module = factor(module, levels=unique(module))) %>%
  mutate(taxonomy = factor(taxonomy, levels=unique(taxonomy)))

fig3A_tax_df <- as.data.frame(rbind(CD_enr_tax_df, UC_enr_tax_df, CD_dep_tax_df, UC_dep_tax_df)) 
fig3A_tax_df$type <- factor(fig3A_tax_df$type, levels=unique(fig3A_tax_df$type))

#plot heatmap
fig3A_heatmap <- ggplot(fig3A_tax_df, aes(x=module, y=taxonomy, fill=n)) + 
  geom_tile(aes(fill=n), color="black", lwd=0.22) + 
  scale_fill_viridis(option="A",direction=-1) +
  theme_bw() +
  facet_grid(cols=vars(type),space="free", scales="free") + 
  theme(strip.background = element_blank(), strip.text.x = element_blank())+
  theme(axis.text.x = element_text(angle=90, size=8.5, hjust=0.95),
        axis.text.y = element_text(size=8.5), axis.title = element_text(size=10),
        legend.background = element_rect(colour = "black", linewidth=0.22),
        legend.position = c(0.08,0.85), plot.margin = unit(c(0, 0.1, 0.5, 0.25), "cm")) + 
  xlab("IBD-relevant modules") + ylab("Chemical subclass or class*")
rm(CD_dep_tax_df, CD_enr_tax_df, UC_enr_tax_df, UC_dep_tax_df)

#--------------------------------------------------------
# Stacked bars for percentage of perturbed features
#--------------------------------------------------------
fig3_modules <- sort(as.numeric(as.character(unique(fig3A_tax_df$module))))
CD_da <- CD_stats[CD_stats$Module %in% fig3_modules, c("Feature_index","Module","Status","qvalue")] %>% arrange(Feature_index) %>% rename(cd_status = 3, cd_qval = 4)
UC_da <- UC_stats[UC_stats$Module %in% fig3_modules, c("Feature_index","Module","Status","qvalue")] %>% arrange(Feature_index) %>% rename(uc_status = 3, uc_qval = 4)
fig3_da_df <- as.data.frame(cbind(CD_da,UC_da)) %>%
  select(1,2,3,4,7,8) %>%
  mutate(cd_status = ifelse(cd_qval < 0.05, cd_status, NA)) %>%
  mutate(uc_status = ifelse(uc_qval < 0.05, uc_status, NA)) %>%
  mutate(final_stat = case_when(cd_status %like% "depleted" & uc_status %like% "depleted" ~ 'CD-dys+UC depleted',
                                cd_status %like% "enriched" & uc_status %like% "enriched" ~ 'CD-dys+UC enriched',
                                cd_status %like% "enriched" & is.na(uc_status) ~ 'CD-dys|UC enriched',
                                uc_status %like% "enriched" & is.na(cd_status) ~ 'CD-dys|UC enriched',
                                cd_status %like% "depleted" & is.na(uc_status) ~ 'CD-dys|UC depleted',
                                uc_status %like% "depleted" & is.na(cd_status) ~ 'CD-dys|UC depleted',
                                cd_status %like% "depleted" & uc_status %like% "enriched" ~ 'CD-dys depleted; UC enriched',
                                cd_status %like% "enriched" & uc_status %like% "depleted" ~ 'CD-dys enriched; UC depleted',
                                is.na(cd_status) & is.na(uc_status) ~"none")) %>%
  group_by(Module, final_stat) %>%
  tally() %>%
  mutate(perc = (n/sum(n))*100)
fig3_da_df <- merge(fig3_da_df, fig3A_tax_df[,c("module","type")],by.x = "Module", by.y = "module")
fig3_da_df <- fig3_da_df[!duplicated(fig3_da_df),]
fig3_da_df$final_stat <- factor(fig3_da_df$final_stat, levels=c('CD-dys+UC depleted',
                                                                'CD-dys|UC depleted',
                                                                'CD-dys+UC enriched',
                                                                'CD-dys|UC enriched',
                                                                'CD-dys depleted; UC enriched',
                                                                'CD-dys enriched; UC depleted',
                                                                'none'))
fig3_da_df$Module <- factor(fig3_da_df$Module, levels = unique(fig3A_tax_df$module))
fig3_da_df$type <- factor(fig3_da_df$type, levels=unique(fig3A_tax_df$type))

#plot da stacked bars
fig3_bars <- ggplot(fig3_da_df[!duplicated(fig3_da_df),], aes(x=Module, y=perc, fill = final_stat)) + 
    geom_col(colour="black", lwd=0.2) + 
    scale_fill_manual(values=c("#204ac8","#809aeb","#DC143C","tomato1","#66c992","#a0d6b4","white")) +
    facet_grid(cols=vars(type),space="free", scales="free") + theme_bw() +
    theme(axis.text.x = element_blank(), axis.title.x = element_blank(),
          axis.title.y = element_text(size=10),
          legend.position = "left", axis.ticks.x=element_blank(),
          axis.text.y = element_text(size=8.5),
          strip.text.x = element_blank(),
          plot.margin = unit(c(0, 0.1, 0.1, 0.1), "cm")) + 
    labs(fill="Perturbation type") + ylab("Features (%)")

#--------------------------------------------------------
# Stacked bars for AVA categories
#--------------------------------------------------------
fig3_ava <- CD_stats[CD_stats$Module %in% fig3_modules, c("Module","AVA")] %>%
  mutate(ava_type = case_when(AVA < 0.1 ~ 'AVA < 0.1',
                              AVA >= 0.1 & AVA < 0.5 ~ '0.5 > AVA ≥ 0.1',
                              AVA < 1 & AVA >= 0.5 ~ '1 > AVA ≥ 0.5',
                              AVA >= 100 ~ 'AVA ≥ 100',
                              AVA >= 10 ~ 'AVA ≥ 10',
                              AVA >= 1 ~ 'AVA ≥ 1'))
fig3_ava <- merge(fig3_ava, fig3A_tax_df[,c("module","type")],by.x = "Module", by.y = "module")
fig3_ava <- fig3_ava[!duplicated(fig3_ava),]  
fig3_ava$Module <- factor(fig3_ava$Module, levels = unique(fig3A_tax_df$module))
fig3_ava$type <- factor(fig3_ava$type, levels=unique(fig3A_tax_df$type))
fig3_ava$ava_type <- factor(fig3_ava$ava_type, levels=c('AVA ≥ 100','AVA ≥ 10','AVA ≥ 1','1 > AVA ≥ 0.5','0.5 > AVA ≥ 0.1','AVA < 0.1'))

fig3_ava_bars <- ggplot(fig3_ava[fig3_ava$AVA >= 0.5,], aes(x=Module)) + 
    geom_bar(aes(fill=ava_type), colour="black", lwd=0.2) +
    facet_grid(cols=vars(type),space="free", scales="free") + theme_bw() +
    scale_fill_manual(values = c("#9e120b","#db7644","#e6ae3e","grey80")) +
    theme(axis.text.x = element_blank(), axis.title.x = element_blank(),
          axis.text.y = element_text(size = 8.5), axis.title.y = element_text(size=10),
          legend.position = "left", axis.ticks.x=element_blank(),
          strip.text.x = element_text(size=9),
          plot.margin = unit(c(0.2, 0.2, 0.1, 0.1), "cm")) + ylab("Features") + labs(fill="Abundance vs anchor (AVA)")

# plot figure3
plot_grid(addSmallLegend2(fig3_ava_bars), addSmallLegend2(fig3_bars), addSmallLegend(fig3A_heatmap), align = "v", ncol=1, rel_heights = c(1.5,1.5,7.5), axis="lr")
```
